name: werewolf_server
description: Server game werewolf with dart.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  socket_io: ^0.9.4
  mongo_dart: ^0.4.4
  dart_jsonwebtoken: ^1.6.2
  equatable: ^1.2.6

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0