name: werewolf_server
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  socket_io: ^0.9.4
  mongo_dart: ^0.4.4
  dart_jsonwebtoken: ^1.6.2

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0